name: ci
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16.x'
      - run: npx pretty-quick --staged
      - run: npx eslint
      - run: npm i typescript
      - run: npx tsc --noemit -p tsconfig.json
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.12.0, 16.x, 17.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test:cov
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
